import type { Metadata } from 'next'
import { AdminBar } from '@/components/Admin/AdminBar/AdminBar'
import { Footer } from '@/components/Footer/Footer'
import { Header } from '@/components/Navigation/Header'
import { fraunces, inter } from '@/styles/fonts'
import '@/styles/scss/globals.scss'

export const metadata: Metadata = {
  title: 'yoga grenoble',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      url: '/icons/favicon-light.svg',
      media: '(prefers-color-scheme: light)',
    },
    {
      rel: 'icon',
      url: '/icons/favicon-dark.svg',
      media: '(prefers-color-scheme: dark)',
    },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <body className={`${fraunces.variable} ${inter.variable}`}>
        <AdminBar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
